---
- name: Ensure Apache Storate Configuration
  hosts: localhost
  vars_files:
    - storage_vars.yml
  tasks:
    - name: 1 Correct partitions exist on /dev/vdb
      debug:
        msg: TODO
      loop: "{{ partitions }}"

    - name: 2 Ensure Volume Groups Exist
      debug:
        msg: TODO
      loop: "{{  volume_groups }}"

    - name: 3 Create each Logical Volume (LV) if needed
      debug:
        msg: TODO
      loop: "{{ logical_volumes }}"

    - name: 4 Ensure XFS Filesystem exists on each LV
      debug:
        msg: TODO
      loop: "{{ logical_volumes }}"

    - name: 5 Ensure the correct capacity for each LV
      debug:
        msg: TODO
      loop: "{{ logical_volumes }}"

    - name: 6 Each Logical Volume is mounted
      debug:
        msg: TODO
      loop: "{{ logical_volumes }}"
