---
- name: Install and start httpd
  import_tasks: install_and_enable.yml
  vars:
    package: httpd
    service: httpd

- name: Open the port for http
  firewalld:
    service: http
    immediate: true
    permanent: true
    state: enabled