---
- name: Update web server
  hosts: webservers
  serial: 2
  tasks:
    - name: Latest version apache installed
      yum:
        name: httpd
        state: latest
      notify:
        - restart apache


  handlers:
    - name: restart apache 
      service:
        name: httpd
        enabled: yes
        state: restarted
